### ISSUE TITLE
`scope` of a property in `contributes.configuration`

### ISSUE THREAD

**Issue by wkordalski** [estruyf/blog-content#6]
Concerns: `content/posts/2023-07-21-visual-studio-code-create-configuration-sections.md`

The post suggests that the `scope` of a property is the name of the category inside which it is contained.
This is not true. `scope` is one of `application`, `machine`, `machine-overridable`, `window`, `resource`, `language-overridable`.

See: https://code.visualstudio.com/api/references/contribution-points#Configuration-property-schema

For this blog post it would be the best to remove the `scope` attributes.

**Comment by estruyf** [comment]
Thanks @wkordalski, I see why this could be confusing. The `scope` was used for building the documentation site, but there was no reference in the article about it. 

I removed it from the code blocks.
